name: solar_energy_prediction
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core

  # Critical
  cupertino_icons: ^1.0.6
  google_maps_flutter: ^2.6.1
  location: 5.0.0
  flutter_platform_widgets: 6.0.0
  http: ^1.2.1
  go_router: ^14.1.2
  provider: ^6.1.2
  google_fonts: ^6.2.1
  intl: ^0.19.0
  flutter_secure_storage: ^9.2.2

  # Can be replaced
  flutter_dotenv: ^5.1.0
  flutter_svg: ^2.0.10+1



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/logos/
    - assets/backgrounds/